<?php
namespace frontend\modules\api;
/**
 * Created by PhpStorm.
 * User: root
 * Date: 05.09.18
 * Time: 21:39
 */
class Module extends \yii\base\Module
{
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}